### ISSUE TITLE
Missing spaces in datafiles

### ISSUE THREAD

**Issue by ekaf** [x-englishwordnet/wndb#1]
Traditionally, all the Princeton datafiles (and also the indexes) have always included two extra spaces at the end of each line. This doesn't seem to be specified anywhere, although OEWN's wndb export also follows this trend. But in  x-englishwordnet /wndb, the extra spaces are missing, which makes it harder to reuse existing code to parse the datafiles, because glosses risk being truncated by two bytes.

**Comment by x-englishwordnet** [comment]
This affects only lines 5, 13, 28 which are empty. They do have the initial 2 spaces as per specification but do not have the trailing 2 spaces before \n, only one.
This was designed to retrieve space in the 1740 bytes slot to include line 29,
"  29 Ground by x-englishwordnet", as an origin stamp.
My idea was that the trailing spaces were meant to provide margins to the text when displayed, and that only text with content could do that (actually only the longest is relevant).
The constraint is I don't want to modify the terms of the copyrights.
The only option is to remove empties to the effect of gaining space.

**Comment by ekaf** [comment]
Actually,it affects all lines, until the end of the files. The license preamble is not a problem. The problem is to parse the synset lines.
